### ISSUE TITLE
Make this /tmp

### ISSUE THREAD

**Issue by frankwiles** [revsys/optimized-python-docker#2]
https://github.com/revsys/optimized-python-docker/commit/51981bb0cabfe46fd9e70fdbbd2018a1c7144b02#commitcomment-26026763

**Comment by gladiatr72** [comment]
I just replaced the example path with `<PATH>` (like the other line).  Varnish doesn't ingest environment variables within its configuration file, so regardless of the placeholder, someone using this would need to set their target directory.  I hesitate to  point it to /tmp due to how quickly the disk cache can grow.
